# Generated by Django 4.2.1 on 2023-05-19 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study_tools", "0002_alter_flashcard_study_set"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flashcard",
            options={"ordering": ["-date_of_creation"]},
        ),
        migrations.AlterUniqueTogether(
            name="flashcard",
            unique_together={("study_set", "term")},
        ),
    ]
